# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import connect.medical_ai_pb2 as medical__ai__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in medical_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostSurgeryFollowUpServiceStub(object):
    """5. 服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/medical_ai.PostSurgeryFollowUpService/CreateSession',
                request_serializer=medical__ai__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/medical_ai.PostSurgeryFollowUpService/Chat',
                request_serializer=medical__ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/medical_ai.PostSurgeryFollowUpService/EndSession',
                request_serializer=medical__ai__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionHistory = channel.unary_unary(
                '/medical_ai.PostSurgeryFollowUpService/GetSessionHistory',
                request_serializer=medical__ai__pb2.GetSessionHistoryRequest.SerializeToString,
                response_deserializer=medical__ai__pb2.GetSessionHistoryResponse.FromString,
                _registered_method=True)


class PostSurgeryFollowUpServiceServicer(object):
    """5. 服务定义
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostSurgeryFollowUpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=medical__ai__pb2.CreateSessionRequest.FromString,
                    response_serializer=medical__ai__pb2.CreateSessionResponse.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=medical__ai__pb2.ChatRequest.FromString,
                    response_serializer=medical__ai__pb2.ChatResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=medical__ai__pb2.EndSessionRequest.FromString,
                    response_serializer=medical__ai__pb2.EndSessionResponse.SerializeToString,
            ),
            'GetSessionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionHistory,
                    request_deserializer=medical__ai__pb2.GetSessionHistoryRequest.FromString,
                    response_serializer=medical__ai__pb2.GetSessionHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medical_ai.PostSurgeryFollowUpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('medical_ai.PostSurgeryFollowUpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostSurgeryFollowUpService(object):
    """5. 服务定义
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medical_ai.PostSurgeryFollowUpService/CreateSession',
            medical__ai__pb2.CreateSessionRequest.SerializeToString,
            medical__ai__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/medical_ai.PostSurgeryFollowUpService/Chat',
            medical__ai__pb2.ChatRequest.SerializeToString,
            medical__ai__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medical_ai.PostSurgeryFollowUpService/EndSession',
            medical__ai__pb2.EndSessionRequest.SerializeToString,
            medical__ai__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medical_ai.PostSurgeryFollowUpService/GetSessionHistory',
            medical__ai__pb2.GetSessionHistoryRequest.SerializeToString,
            medical__ai__pb2.GetSessionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
